#pragma once
#include "stdafx.h"

enum class MessageType : uint8_t
{
	JETBOT_CONNECT		= 0U,
	JETBOT_DISCONNECT,

	JETBOT_INFORMATION_REQUEST,

	CONTROLLER_CONNECT,
	CONTROLLER_DISCONNECT,

	CONTROLLER_JETOBT_INFORMATION_REQUEST,

	CONNECT_CHECK,
};